### ISSUE TITLE
Integrating Translation-helps, bible reference and workspace rcl inside Autographa

### ISSUE THREAD

**Issue by Ashersam** [friendsofagape/autographa#142]
Integrating Translation-helps, bible reference and workspace RCL inside Autographa with necessary UI/UX changes.

**Comment by LijuJacob08** [comment]
above mentioned things are visible in the editor page(3page), hence moving this to done.
attaching the screenshot for the same.
![image](https://user-images.githubusercontent.com/93033055/144437079-2e382d3f-3cdc-42d0-8866-d03e872f3d22.png)
