### ISSUE TITLE
Snackbars - Home Page

### ISSUE THREAD

**Issue by samuelanthrayose** [friendsofagape/autographa#160]
A component which receives short notification or status passed.

**Comment by LijuJacob08** [comment]
snackbars are included ,following are the few of them:-
-after saving the profile page it is visible
![image](https://user-images.githubusercontent.com/93033055/146255946-620780ab-009f-4057-8d49-270e7e18159e.png)
-when project is exported
![image](https://user-images.githubusercontent.com/93033055/146256518-4d1ab649-730a-47de-90be-73fabb4ef9b8.png)
 moving to done
