### ISSUE TITLE
Type Validation of Version and Abbreviation 

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#259]
Issue Description: In the version field, special characters and symbols -@/% and --- which may not make sense  if only such characters are allowed. Similarly, in the abbreviation field ,in addition to letters and numbers, special characters are allowed. 

Observation :Special characters and symbols are allowed in Version and Abbreviation fields.

Expected behavior :A type validation of  characters allowed in the Version and Abbreviation  that allows strings (letters ) and numbers would help
An alert displaying the allowed characters would help the user.

**Comment by vipinpaul** [comment]
Added the Validation hook and connected it with the New/Edit project page
