### ISSUE TITLE
Advanced Settings -Accurate highlighting of selected tab  for OT/NT/All books does not happen

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#267]
Issue Description : The highlighting of  the selected tab  is not accurate on hovering upon OT/NT/All books
Steps :
In advanced settings, click Add, and select the filter for OT/NT/All books,
Observation : The header does not accurately highlight the selected tab on hovering upon OT/NT/All books.
Expected behaviour:  On hovering upon OT/NT/All books ,the highlighting of the selected tab should be accurate

**Comment by LijuJacob08** [comment]
Observations are:
UI has been updated :-(Discussed this- were a part of  requirement changes)
- text Canon selection is replace by Scope.
- dropdown is replaced by buttons which work like option button ie only one can be selected at a time.
- buttons are highlighted when whichever is selected.
looks good moving to done.

All Books
![image](https://user-images.githubusercontent.com/93033055/144228383-b83caac4-2ed8-4021-a2a8-96583640cb39.png)

OT
![image](https://user-images.githubusercontent.com/93033055/144228489-2f2de427-4666-4eb9-85c4-413ae91476f4.png)

NT
![image](https://user-images.githubusercontent.com/93033055/144228672-efd03285-3f22-474a-a287-8d294ebadc6c.png)

Custom
![image](https://user-images.githubusercontent.com/93033055/144228878-cacb3f24-a516-4614-a53e-676c354ac55a.png)
