### ISSUE TITLE
Mode -The Bible mode has a down arrow but does not open up a drop down box

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#268]
Mode -currently  Bible has a down arrow indicating a  drop-down ,
Observation :On selecting the down arrow , there is no  dropdown. 
Expected Behaviour : It would be better if clicking on the down area opens  up a drop down llist with possible options
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
.

**Comment by Ashersam** [comment]
@AnnCherianA The dropdown shows modes of the project(text translation, audio, obs etc.) expected in future releases. Now it should be hidden.

**Comment by LijuJacob08** [comment]
removed the down arrow from the Bible button. looks good and moving to done.
![image](https://user-images.githubusercontent.com/93033055/144230232-95ef2a83-a4ed-49b1-a8f1-a8afaf8a63a4.png)
