### ISSUE TITLE
Date -Time Zone format incorrect

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#269]
Issue: Currently the date and  time zone does not display in the proper format of a Date and Time Zone
Observed :The date,/ time zone format is not formatted correctly 
Expected Behaviour: The date and time zone are to be displayed in the right format

**Comment by LijuJacob08** [comment]
looks good moving to done.
![image](https://user-images.githubusercontent.com/93033055/144434301-0f49a4e8-4985-4e6d-bd9d-ee105b3003a4.png)
