### ISSUE TITLE
Status displays as finished for a newly created project

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#270]
For a newly created project, the status displays as finished.

**Comment by LijuJacob08** [comment]
observation:
earlier it was not noticeable whether the project was created or not , as after saving no snack bar was displayed (with message like project created successfully) nor the page redirection was happening. now ,verified that as soon as the New Project details are saved the page is redirected to the Project list page where one can see the newly created project. Looks good hence moving this to done.
