### ISSUE TITLE
Language filters -Unable to clear filters on closing

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#272]
Issue Description : The filters Malayalam/Arabic does not clear on clicking the close button
Expected : On clicking the close button, the selected filters Malayalam /Arabic should be closed.

**Comment by LijuJacob08** [comment]
can be closed as the UI has been updated it's no longer an issue.
![image](https://user-images.githubusercontent.com/93033055/144411937-0978d398-e0d2-4d2d-8702-c3431e55e97f.png)
