### ISSUE TITLE
Reference History

### ISSUE THREAD

**Issue by Ashersam** [friendsofagape/autographa#276]
* [x] Keep reference history of a particular project
* [x] Independent Navigation for each panel (each panel should have its own navigation along with group navigation)
* [x] Save navigation of each panel as history 
* [x] Remove navigation bar from reference resources on unscrolls

**Comment by JesniJ** [comment]
@LijuJacob08 Did you test this issue , if yes please move it to done

**Comment by LijuJacob08** [comment]
actually I don't remember how this issue was missed, this issue was created for some Autographa 2.0 beta version(not sure which version it was). currenlty Autographa 2.3.2 is the latest release. so will test and confirm the changes in the latest version.
