### ISSUE TITLE
Adding AJV-validator

### ISSUE THREAD

**Issue by vipinpaul** [friendsofagape/autographa#288]
Update the code to create a better burrito
- [x]  Adding version and Abbr. in burrito, remove the project name.
- [x]  setting CanonType and CanonSpec
- [x] Adding language code.
- [x] validate the burrito before export.
- [x] Modify the special characters in the licence.
- [x] Project folder name should have the project name and key.
- [x] Displaying project ID in Project List.
- [x] Validating burrito before Import.
- [x] Update the code of Import Burrito.

**Comment by LijuJacob08** [comment]
verified the following-
Project id displayed in Project list
![image](https://user-images.githubusercontent.com/93033055/146252649-af23f9c9-dbda-4d61-b9de-f537451b6be8.png)

validating  burrito before import

and rest were backend related work(As discussed with @vipinpaul )
moving to done.
