### ISSUE TITLE
Mark the required fields with asterisk.

### ISSUE THREAD

**Issue by vipinpaul** [friendsofagape/autographa#307]
Using asterisk(*) for required fields.
**New Project Page**
- [x] Project Name
- [x] Abbreviation
- [x] Target Language
- [x] Versification Scheme
- [x] Canon Specification
- [x] Licence
**Profile Page**
- [x] App Language

**Comment by LijuJacob08** [comment]
Looks good moving to done.
New Project Page
![image](https://user-images.githubusercontent.com/93033055/144234669-c1f7012b-8500-41ff-882c-b71a77151473.png)
 
Profile Page
![image](https://user-images.githubusercontent.com/93033055/144234858-ac82c85e-e265-4cdf-b6cb-c8f18d77667f.png)
