### ISSUE TITLE
Updating New Project Page.

### ISSUE THREAD

**Issue by vipinpaul** [friendsofagape/autographa#309]
- [x] Removing of version and abbreviation.
- [x] Adding abbreviation for Project Name.
- [x] Updating the Burrito.
- [x] Data loading issue.
- [x] Store Project name in Burrito instead of ag-settinngs.json.

**Comment by LijuJacob08** [comment]
checked:-
 -Removing of version and abbreviation.
 -Adding abbreviation for Project Name.
![image](https://user-images.githubusercontent.com/93033055/144435139-8c41ace7-cdfc-4022-aeaa-285291641d99.png)
 - and  verified that data is also loading.
 looks good ,moving to done.
