### ISSUE TITLE
Search tab returns client side exception error

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#313]
Search tab -On searching for a project in the project page, a client-side exception error is thrown.

In the Projects Page, on trying to enter words in the Search tab, it displays an error.
![image](https://user-images.githubusercontent.com/74647279/135083137-5bea4f4d-fc9d-4a35-8dd6-463c9402a79c.png)

On searching for projects, the search tab is to display the project

**Comment by LijuJacob08** [comment]
looks good moving to done.
Before search
![image](https://user-images.githubusercontent.com/93033055/144226205-5714464f-9a4e-4583-9ffd-e02fa08db3a1.png)
After search
![image](https://user-images.githubusercontent.com/93033055/144226606-56ab1870-0b2d-4a6a-bab5-e7a2c8a6500c.png)
