### ISSUE TITLE
A new project created shows as Undefined 

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#314]
After creating a new project, the title shows as Undefined. 
![image](https://user-images.githubusercontent.com/74647279/135263021-eae9b0c9-5a7f-469d-b23e-d91b7725c13b.png)

**Comment by LijuJacob08** [comment]
looks good can be moved to done.
![image](https://user-images.githubusercontent.com/93033055/144413371-7addbe77-6eb0-436a-ba36-68190c3658ca.png)
