### ISSUE TITLE
extra char () shows in Export Project option

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#315]
There is an extra character () that is displayign after Export Project title
Expected : To Remove the extra character and displaying the title as Export Project 

![image](https://user-images.githubusercontent.com/74647279/135270618-cba99e7a-2d37-48be-bf48-d241654a183f.png)

**Comment by LijuJacob08** [comment]
it's fixed and can be moved to done.
attaching the screenshot
![image](https://user-images.githubusercontent.com/93033055/139626000-8cff7c86-1688-4187-a876-e4e473a8274c.png)
