### ISSUE TITLE
The Export icon does not open to a new window

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#316]
The folder icon(export) does open to a new window on clicking 

![image](https://user-images.githubusercontent.com/74647279/135271035-93c29d7c-23d8-4b10-8426-a802cb4d0487.png)

**Comment by AnnCherianA** [comment]
In the Projects page, there is a folder /edit icon which does not work or open to a new window on clicking

**Comment by LijuJacob08** [comment]
following was tested on Ag2.0 beta3
export and edit options are moved under more options( which is 3 dot icon), here  clicking on export option open a new window -> browse to desired location inorder to export the project and on clicking the edit option will open to the edit page where the project details can be edited  , attaching the video for the same.  It looks fine and can be moved to done.

https://user-images.githubusercontent.com/93033055/142778836-86191bce-b954-426e-b839-3a76e57b0f5b.mp4
