### ISSUE TITLE
A tooltip for all the icons in the app 

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#317]
ICurrently most of the icons do not have a tooltip , not giving the user a clear idea of the feature.
It would be very helpful to the user to include a tooltip on hovering the icons 
![image](https://user-images.githubusercontent.com/74647279/135272200-3ec87cd3-d91f-40cc-a2fb-654d80894b0d.png)

**Comment by LijuJacob08** [comment]
fixed and can be moved to done.

![image](https://user-images.githubusercontent.com/93033055/139628366-30a69d27-1c99-4bf6-9178-70d6ec5e8395.png)

**Comment by LijuJacob08** [comment]
in Beta 4
certain changes were made
included the icon on header which works like label to the star/ unstar and open project icon was removed from each row.
![image](https://user-images.githubusercontent.com/93033055/144803058-e5723283-da31-402b-a014-09c9e78b9621.png)
 hence moving to done.
