### ISSUE TITLE
Bookmark to open to  the selected chapter

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#318]
On clicking a bookmark, it does not open to the particular chapter.
![image](https://user-images.githubusercontent.com/74647279/135272852-8a79678e-5fa3-40e6-a919-817c17dac7d7.png)

Selecting a bookmark should be opening to the chapter associated

**Comment by LijuJacob08** [comment]
looks good moving to done.
attaching the recording for the same.

https://user-images.githubusercontent.com/93033055/146251357-706e98f8-f6e4-401b-900b-09f52b0a8f40.mp4
