### ISSUE TITLE
Resources Tab- The Close button image not loading 

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#319]
The close button icon does not loaded properly in the Resources Tab,
Impacts the following options

Translation Words
Notes
Bible
Questions
Map
Commentary 
![image](https://user-images.githubusercontent.com/74647279/135273563-6bac9599-d7f8-41aa-8c65-605bd2c80f19.png)

**Comment by LijuJacob08** [comment]
looks good  moving to done.
![image](https://user-images.githubusercontent.com/93033055/144231893-35f84ff6-80b2-4ac7-90b1-b58e35f6ceae.png)
