### ISSUE TITLE
Space between Translation and Words

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#320]
There is to be a space between Translation and Words in the Resources Tab

![image](https://user-images.githubusercontent.com/74647279/135274070-2f5cfa16-cb42-4920-a01e-3db5c0434bb5.png)
**

**Comment by LijuJacob08** [comment]
looks good moving to done.
![image](https://user-images.githubusercontent.com/93033055/144229378-332d3b6d-7601-44e0-a24f-01aadc68db1e.png)
