### ISSUE TITLE
Replace pointer by arrow for non-editable text

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#321]
The click pointer gives the user the idea that the text is clickable
![image](https://user-images.githubusercontent.com/74647279/135274529-d97d6dc0-b9a6-4cc4-9e21-f37f13e6f98b.png)

Replace pointer by arrow for text that cannot be edited.

**Comment by joelthe1** [comment]
Thanks for the screenshot @AnnCherianA!

I think what we would want is to have a `...` icon with a small drop-down which has an entry called `Verse per line` (which is a toggle item) which allows the user to toggle the view based on their preference. I think we can default this to true.

**Comment by LijuJacob08** [comment]
looks like it's still there.

https://user-images.githubusercontent.com/93033055/139622404-4a48041d-a99d-45b8-9060-7caa7343e510.mp4

**Comment by LijuJacob08** [comment]
Issue was that it was showing hand pointer when pointing in  between the two verse ,where it was giving the impression that it was clickable item.
Observations :
UI has been updated ,in which each verse is placed in a new line where text can be easily added. 
adding the screenshot for the same.
![image](https://user-images.githubusercontent.com/93033055/144807211-9782300b-f27d-4ec3-a48e-9db4457fd05c.png)

moving to done.
