### ISSUE TITLE
Custom field does not list always in the Canon specification tab

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#322]
In the Projects page, under Advanced Settings,the option Custom does not list always in the Canon specification tab
![image](https://user-images.githubusercontent.com/74647279/135279905-80eee5ed-56dd-46af-902e-5428a893622b.png)

The Custom field is to be listed at all times in the Canon Specification drop down

**Comment by LijuJacob08** [comment]
**observation** : 'Canon specification' text is changed to 'scope'(As part of requirement change) and  the UI for the the dropdown is changed to buttons which works something like radio button on clicking on each whould list out the the respective books.  custom button is visible now. looks fine moving to done.
![image](https://user-images.githubusercontent.com/93033055/143399637-0b2a0c99-9536-407f-99d0-b59f6ac8ead0.png)
