### ISSUE TITLE
Selecting RTL lists LTR languages in the drop down

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#323]
On selecting script direction as RTL, the LTR languages should not be displayed in the drop down
![image](https://user-images.githubusercontent.com/74647279/135278103-cae68ca2-a5a4-4588-947f-e1841a7eee46.png)

**Comment by Ashersam** [comment]
@AnnCherianA
Yes, good suggestion...but right now we cant add that filter. Because scripture direction data is not available with the language backend file.
Right now we collect scripture direction from the user and set that for the corresponding project (inside metafile)

**Comment by LijuJacob08** [comment]
UI has been updated , here when we add a language for say Urdu  it will visble in the in the dropdown only once the project is saved. here RTL and LTR are just label which tells the whether the selected lang is RTL or LTR.
Attaching the recording for the same.

https://user-images.githubusercontent.com/93033055/146263620-53bca21c-ad5c-49f4-8800-ea4f0ac8822a.mp4

moving to done.
