### ISSUE TITLE
Enhancement -A down arrow indicating a drop down would be useful 

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#324]
A normal text box for drop down included does not clearly indicate to the user that  a drop down follows

Under Advanced  settings, the versification, canon specification boxes etc do not have a clear indication of a drop down .
A down arrow or any suitable icon would be useful to indicate about the drop down. 

A similar drop down as shown beside Advanced Settings tab would be fine. 

![image](https://user-images.githubusercontent.com/74647279/135280861-7d81d5fa-6827-4541-abda-d0e7945c00b4.png)

**Comment by LijuJacob08** [comment]
looks fine ,can be moved to done.

![image](https://user-images.githubusercontent.com/93033055/142778593-155d7562-b8b7-4404-9c44-5ddbe856f459.png)
