### ISSUE TITLE
Spelling error -Target Language spelt incorrectly 

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#325]
In the Projects Page, the Target Language is to be spelt correctly

![image](https://user-images.githubusercontent.com/74647279/135282292-395b4f3c-c001-4275-a96b-444629160c0e.png)

**Comment by LijuJacob08** [comment]
Tested in Ag 2.0 Beta3
looks fine and can be moved to done.
![image](https://user-images.githubusercontent.com/93033055/142779111-0d5a7397-2580-4d1b-835c-54f4ed7d2212.png)
