### ISSUE TITLE
NIV To be correctly expanded as New International Version

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#326]
In the Versification scheme, NIV is currently displayed as New Internation  Version.
It is to be correctly displayed as New International Version 

![image](https://user-images.githubusercontent.com/74647279/135283066-f13dfebc-bf1e-48f1-aca8-c5df61b04915.png)

**Comment by vipinpaul** [comment]
UI is been updated.

**Comment by LijuJacob08** [comment]
As the the UI has been updated ,looks fine ,so moving done.
![image](https://user-images.githubusercontent.com/93033055/144218318-12fcbcd1-7d7d-4fbc-903f-6443f3b35325.png)
