### ISSUE TITLE
The sub modes under Bible does not open to new windows 

### ISSUE THREAD

**Issue by AnnCherianA** [friendsofagape/autographa#327]
The modes under Bible -does not open to a new tab on clicking

Translation
OBS
Audio
MT

![image](https://user-images.githubusercontent.com/74647279/135283921-ff2f8714-049a-4f93-ab8d-9a52c8c515a1.png)

**Comment by LijuJacob08** [comment]
looks like button's functionality is disabled.
![image](https://user-images.githubusercontent.com/93033055/139623678-506d4561-6846-4db9-8d17-23737bcc18f3.png)
