### ISSUE TITLE
UI Fixes for Beta Release

### ISSUE THREAD

**Issue by joelthe1** [friendsofagape/autographa#340]
The following issues need fixing before release the next beta version:
- [ ] Drop downs in projects page need fixing along with alignments of the components.
- [ ] Edit license: The dialogue box needs to be made bigger. The 'preview' should show up as a slider button.
- [ ] Greyed background on project name and versification scheme in edit project mode
- [ ] Side pane in the profile page needs fixing
- [ ] Login page needs fixing. SVGs and username box
- [ ] Projects page listing header seems inconsistent.
- [ ] The projects listing should have clickable instead of the external link icon. It should have on-hover state. Also, on desktop the projects page was showing with a scroll bar and being adaptive. We also need a search icon and needs alignments fixes.
- [ ] The import project dialogue can be made smaller. Same for export dialogue.
- [ ] Font selector needs aligning.
- [ ] Resources selector dialogue needs fixing.
- [ ] Resource section should have a 'load resource' icon instead of 'settings' icon. The 'expand' icon doesn't work.
- [ ] Close section should have confirmation box.
- [ ] Profile image needs to be made generic.
- [ ] The side-bar in the editor page should slide-in from the right.
- [ ] Add option for paragraph view and verse per line view in the editor option

**Comment by arpitjacob** [comment]
- [x] Drop downs in projects page need fixing along with alignments of the components.
- [x] Greyed background on project name and versification scheme in edit project mode.
- [x] Side pane in the profile page needs fixing
- [x] Projects page listing header seems inconsistent.
- [x]  Profile image needs to be made generic.

**Comment by arpitjacob** [comment]
- [x]  Resources selector dialogue needs fixing.
- [x]  Resource section should have a 'load resource' icon instead of 'settings' icon.
- [x]  Back button on editor page, UX/UI fix 
- [x]  Edit license: The dialogue box needs to be made bigger. The 'preview' should show up as a slider button.
