### ISSUE TITLE
Resourses import from Common folder

### ISSUE THREAD

**Issue by Ashersam** [friendsofagape/autographa#341]
- Create and fetch resources from the common folder
- Display all the resources on the same resource popup
- Remove app reload and add instant display on import

**Comment by LijuJacob08** [comment]
Looks good moving to done.
-Display all the resources on the same resource popup
![image](https://user-images.githubusercontent.com/93033055/144411091-01176a9b-40e3-4e87-a34c-f9eac66a7ac3.png)

-Remove app reload and add instant display on import
![image](https://user-images.githubusercontent.com/93033055/146262239-59815aa9-fde7-4644-8298-ec27704000d1.png)

**Comment by JesniJ** [comment]
@LijuJacob08 Did you test this issue , if yes please move this to the proper tab

**Comment by LijuJacob08** [comment]
this issue was tested , moving this to done.
