### ISSUE TITLE
Add Edit Project page.

### ISSUE THREAD

**Issue by vipinpaul** [friendsofagape/autographa#343]
- [x] Allowing the user to edit the project settings.

And update a few UI and functionalities.
- [x]  Rename Canon Specification to Scope.
- [x] In scope rename the Custom to Other.
- [x] Inter-change the position of versification and scope.
- [x] Change the arrow directions in Project Listing.
- [x] Disable versification in Edit project page.
- [x] Replace the title with id for displaying versification.

**Comment by LijuJacob08** [comment]
list of things verified:-
Allowing the user to edit the project settings.
![image](https://user-images.githubusercontent.com/93033055/144404068-208c1728-fe83-4c44-8f88-6eabc4acef35.png)

update a few UI and functionalities.

 Rename Canon Specification to Scope.
![image](https://user-images.githubusercontent.com/93033055/144404457-1eb55a60-81fa-4a42-837b-8dfa4eadfe9f.png)

 In scope rename the Custom to Other.(Later changed back to Custom)
![image](https://user-images.githubusercontent.com/93033055/144404636-fa089fc0-3b3f-40f7-8d2b-219df9adedb1.png)

 Inter-change the position of versification and scope.
![image](https://user-images.githubusercontent.com/93033055/144404788-f76eefc7-f0e9-480e-9f10-721f90ebd652.png)

 Change the arrow directions in Project Listing.
![image](https://user-images.githubusercontent.com/93033055/144404968-cd32ab2c-9710-49f7-846f-7ddf7d804a60.png)

 Disable versification in Edit project page.
![image](https://user-images.githubusercontent.com/93033055/144405819-08783722-d3d2-46f8-a962-ac287f1eacb1.png)

 Replace the title with id for displaying versification.
![image](https://user-images.githubusercontent.com/93033055/144406065-d91d844e-95fd-42fa-872e-b50f5f1aa07f.png)
  
looks good moving to done.
