### ISSUE TITLE
when user tries to  reload,it does not work everytime 

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#351]
(Autographa 2.0 beta 2)

**Issue Description**:-
few cases, page reload  is not working, restarting the app is required(eg when on a new page in order to create a new project, if one chooses to reload the page it will load a blank page with menu bar on the top. one can't navigate back two the previous page )
 
* in the below video - part where i navigated  view -> reload is not visible 

https://user-images.githubusercontent.com/93033055/139403153-ef791e93-c495-4eb6-83fc-e5da97f5c781.mp4

**Comment by vipinpaul** [comment]
In this, the menu is been removed.
