### ISSUE TITLE
expand and collapse arrows

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#352]
(Autographa 2.0 beta 2)
**Issue Description**:- 
arrows used to collapse and expand the project details are used otherway round-(in projects page )
 
expand button - up arrow (should be down)
![image](https://user-images.githubusercontent.com/93033055/139407903-e509034d-5cd6-4df6-b19c-8b6a48212649.png)

collapse button - down arrow (should be up )
![image](https://user-images.githubusercontent.com/93033055/139408289-83bea036-413a-4689-b9ca-1bd975cfc7c8.png)

**Comment by vipinpaul** [comment]
This is been fixed.

**Comment by LijuJacob08** [comment]
looks good moving to done.
collapsed state:
![image](https://user-images.githubusercontent.com/93033055/144223485-0962ce32-81f2-4082-8a1f-0396e44e8f98.png)
Expand state:
![image](https://user-images.githubusercontent.com/93033055/144223804-e489e3c0-e1dc-4d49-becc-78af01e6dcd8.png)
