### ISSUE TITLE
No font style other than sans-serif is visible 

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#353]
(Autographa 2.0 beta 2)

**Issue Description**:-
Font style selector in the edit mode can't be changed from sans serif( open a project ->File menu-> default font family->san-serif)

![image](https://user-images.githubusercontent.com/93033055/139411101-8abd0d55-1320-4f0b-bce0-130e73ef83b8.png)

**Comment by vipinpaul** [comment]
It is working. Can you test it again?

**Comment by LijuJacob08** [comment]
looks fine moving to done.
![image](https://user-images.githubusercontent.com/93033055/144219067-e5cac253-48cf-4ef4-9ba3-f4fc081e2f75.png)
