### ISSUE TITLE
licence drop down needs a visible sroll bar and last few values are barely visible

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#354]
(Autographa 2.0 beta 2)

**Issue Description**:-
needs a visible scroll bar in the Licence/license dropdown(for selecting the type of license) and end even with scroll bar the  last few options are barely visible/accessible.

https://user-images.githubusercontent.com/93033055/139422621-19e4f44d-6191-4862-b7af-ac83814471c8.mp4

**Comment by vipinpaul** [comment]
The issue is been fixed, scrollable till the last option.

**Comment by LijuJacob08** [comment]
for scrollbar had created a separate issue-[385](https://github.com/friendsofagape/autographa/issues/385) looks good  moving to done.
![image](https://user-images.githubusercontent.com/93033055/144225056-81c1cc99-462d-4dac-ba15-047945921302.png)
