### ISSUE TITLE
Expand button is visible for Export option (Project list page)

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#371]
**Autographa 2.0 beta 3**
when have more than one project list in the project list, click on expand button of the project( should not be the last project)-> click on 3 vertical dots( which is more options) , will dropdwon to optoins which are Edit and Export ,here able to see the expand button of the  succeeding project visible in the export.(looks like Export option/button is transparent).

**Expected Behaviour**: Export button should not be tansparent else it's providing an impression that the Export option  expandable.

In the following screenshot Expand button which is visible here is of second project which is hindi to Tamil is visible inside Export option of English to tamil Project
![image](https://user-images.githubusercontent.com/93033055/142839405-b66cef04-80b0-4a2c-b86b-f46c89f0dc7c.png)

**Comment by vipinpaul** [comment]
This is been fixed.

**Comment by LijuJacob08** [comment]
looks good moving to done.
![image](https://user-images.githubusercontent.com/93033055/144222597-735baf0d-586a-422c-a26a-05647c40832f.png)
