### ISSUE TITLE
Resource  modal view is clipped and Upload button not visible for Bible tab

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#372]
Autographa 2.0 beta3
Issue Desciption:
Resource  modal/panel not loading completely ie why things below  translation  Questions are  not visible. And '**Upload**' button not visible in Bible tab.
 Resource modal needs a UI fix.(This  was working  fine in the previous version -[regression])

![image](https://user-images.githubusercontent.com/93033055/142841017-1e3d25fe-5502-4809-9e76-79b25851d47b.png)

**Comment by vipinpaul** [comment]
This is been fixed.

**Comment by LijuJacob08** [comment]
looks fine moving to done.
![image](https://user-images.githubusercontent.com/93033055/144221561-518085e8-3954-4618-838a-2792692a526e.png)
