### ISSUE TITLE
no ‘Back’ button in editor in editor page

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#373]
**Issue Description** :There is no ‘Back’ button in editor in editor page, here Project name is working as back button.
**Expected Behaviour**:  need a seperate back button.

![image](https://user-images.githubusercontent.com/93033055/142841753-229fa125-da86-46ac-8aa9-b8abff7cd2b1.png)

**Comment by vipinpaul** [comment]
Added the back button.

**Comment by LijuJacob08** [comment]
looks fine moving to done.
![image](https://user-images.githubusercontent.com/93033055/144221155-92679625-0ee3-4f2d-b0a8-ba9fec50794d.png)
