### ISSUE TITLE
clicking on dropdown affecting UI of the New/Edit Project page

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#374]
Autographa 2.0 beta3
**Issue Description**:
clicking  on scope/verification scheme/licence dropdowns which are under additional settings(while creating a new project) is affecting the display/UI of page.
Attaching the video for the same

https://user-images.githubusercontent.com/93033055/142844110-1291b5d9-2a1e-4230-9647-d134b8e9692a.mp4

**Comment by vipinpaul** [comment]
This is been fixed.

**Comment by LijuJacob08** [comment]
looks good moving to done.

https://user-images.githubusercontent.com/93033055/144233855-f36c6322-ee26-4ae7-a9dc-1c7cb911840e.mp4
