### ISSUE TITLE
Incorrect alignment of Browse button in Export 

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#375]
**Issue**
-Browse button should be next to the Export file path’s textbox.

Attaching the screenshot
![image](https://user-images.githubusercontent.com/93033055/142847208-46c9fded-ec12-48e8-8a68-d8f1fdfd50ae.png)

**Comment by vipinpaul** [comment]
Fixed.

**Comment by LijuJacob08** [comment]
looks fine moving to done.
![image](https://user-images.githubusercontent.com/93033055/144220806-e7600b1f-8ab6-4123-9c45-126e8924e1f4.png)
