### ISSUE TITLE
close ,cancel and save button not working 

### ISSUE THREAD

**Issue by LijuJacob08** [friendsofagape/autographa#376]
Autographa 2.0 Beta 3
**Issue Description**:
In the New/ Edit Project page ->clicking on Edit button next all books dropdown which is
![image](https://user-images.githubusercontent.com/93033055/142849112-e49d4e1c-4c3a-4c29-9389-e61fbb46bc12.png)

which open All book modal
![image](https://user-images.githubusercontent.com/93033055/142851742-a1a00587-ea6b-4479-b279-67a44d1de98f.png)
here, **Close, Cancel  and Save**(available for Edit Projects page) buttons are not responding.Hence Restarting the app is required.

 **Expected behaviour**: should close the modal in case of Cancel /close icon  button and should save the changes on clicking on Save Button.
Attacing the screenshots 
-New Project page(only Close and Cancel Buttons)
![image](https://user-images.githubusercontent.com/93033055/142851482-b29e235e-4f83-49eb-bcbd-7cb0ca826cab.png)
-Edit Project page(Close, Cancel and Save buttons are available)
![image](https://user-images.githubusercontent.com/93033055/142851999-d795783a-0d72-4629-ac7f-b1eb41cac370.png)

**Comment by vipinpaul** [comment]
Updated the UI and fixed the button issue.

**Comment by LijuJacob08** [comment]
looks fine moving to done.

**Comment by LijuJacob08** [comment]
UI has been updated and button is also fixed. 
Attaching the recording for the same.

https://user-images.githubusercontent.com/93033055/146196971-8fb9e65f-2557-49b6-ab58-9b9423c09822.mp4


moving to done.
