### ISSUE TITLE
Validation and Fix for i18 Internationalization 

### ISSUE THREAD

**Issue by sijumoncy** [friendsofagape/autographa#516]
This issue is a connected issue to make i18n string to support internationalization (#460 ) . 
Things issue aims

-  Look back to the internationalization i18 after getting 1 more language other than English and fix i18 missed support of strings in the earlier PR ( Implementing i18 Internationalization )

**Comment by joelthe1** [comment]
This can now be done using https://github.com/friendsofagape/autographa/compare/development...Samuel-Kim:patch-1 and https://github.com/friendsofagape/autographa/compare/development...Samuel-Kim:patch-2.

Not sure what the differences are.

**Comment by sijumoncy** [comment]
Added 3 languages En, Ru, Hi
