### ISSUE TITLE
Implementing OBS Editor in AG

### ISSUE THREAD

**Issue by vipinpaul** [friendsofagape/autographa#528]
- [ ] Add Editor panel to OBS Project, replace the white part ie usfm editor only and reuse the other code, When opening a project show this by default instead of the usfm editor and hide bookmarks for now and later we can add it as a enhancement
![image.png](https://images.zenhubusercontent.com/5ceb9955d8501ed6b9d3368a/ef906e19-fa63-4fa6-b23b-32ba8ab7abb5)

**Comment by sijumoncy** [comment]
Pending to Implement Bookmarks for OBS Mode ( Enhancement )
