### ISSUE TITLE
Speech to Text

### ISSUE THREAD

**Issue by joelthe1** [friendsofagape/autographa#553]
## Speech to Text
Ability to convert speech to text within the Audio Recorder Mode via APIs.

**Comment by sijumoncy** [comment]
Findings
-[Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) is the one thing help to convert Audio (microphone input) to text real time in JS. But I am not able to find an option to pass a audio file directly to it and generate a text from it
- [Python have package to convert audio file to text ](https://stackoverflow.com/questions/32587015/audio-file-to-text-file-python) with set of  [language support](https://stackoverflow.com/questions/14257598/what-are-language-codes-in-chromes-implementation-of-the-html5-speech-recogniti/14302134#14302134)

**Comment by joelthe1** [comment]
It does look like we can't feed in files: https://stackoverflow.com/questions/46267816/is-there-a-way-to-use-the-javascript-speechrecognition-api-with-an-audio-file

I think we can design the UI so that it works only when the user is actually recording from the mic. In the future, we plan to shift to using Vachan API to power this for us.

**Comment by sijumoncy** [comment]
Implementing speech to text using the web speech recognition api is not possible in Electron JS. We have tried with different implementation in our app but nothing makes it worth. According to discussion in the web shows the feature of speech recognition is disable in chromium ( electron using chromium ) and web speech recognition api only work in browser.
We have tired in the dev version of autograpaha web with same implementation and found working . We are not able to find anything useful to make the same working in electron yet. 
![image](https://user-images.githubusercontent.com/72241997/210537964-308c412b-eed8-4013-b625-ef899bb1d262.png)

Work around code as draft PR for reference : https://github.com/friendsofagape/autographa/pull/741

**Comment by vipinpaul** [comment]
Since this can't be added to the electron app, we have added the feature to the Audio recorder RCL - https://recorder-rcl.netlify.app/#/SpeechToText
