### ISSUE TITLE
MacOS App and Installer Icon Incorrect

### ISSUE THREAD

**Issue by jag3773** [friendsofagape/autographa#600]
The 2.1.0 app for Mac does not use the Ag icon on installation or for the app on the launchpad screen. It's using the electron icon instead.

<img width="737" alt="Screen Shot 2022-07-21 at 8 36 18 AM" src="https://user-images.githubusercontent.com/107731/180216015-972142f4-651c-4ae8-b437-ce0632ffda1d.png">

**Comment by vipinpaul** [comment]
Using the icon with **icns** extension will solve this issue for both Mac OS and Linux.

**Comment by vipinpaul** [comment]
App icon is working in both Mac and Linux
![cfd20fac-c757-4d8d-b7b5-c784b691cb00](https://user-images.githubusercontent.com/37212471/206460541-ef2adb33-3d96-4880-bb7b-39f51bdd5d85.jpg)
