### ISSUE TITLE
need to fix error while testing the app

### ISSUE THREAD

**Issue by Bobbykumar706584** [friendsofagape/autographa#683]
- [x] The issue is when we open the same resource in multiple panes  and  delete the resource, it will remove the pane contents and heading 

here is the link https://www.loom.com/share/f32bc86dd28342c1aee1e654d3ef5114

- [x] audio bible does not load
https://www.loom.com/share/2126508e752a4cf4a83fed49ab5014d6
https://www.loom.com/share/0b7332b4776a43198880e7c2dfd1b258
Assign to @vipinpaul 

- Lock navigation and bookmark do not work. Assign to @samueljd 
- [x] Remove the import button from the archived project.

**Comment by vipinpaul** [comment]
The issue are there for Bookmark and Lock functionality
