### ISSUE TITLE
Issues in 2.2.0

### ISSUE THREAD

**Issue by vipinpaul** [friendsofagape/autographa#692]
- [x] There was a breakage in the Autographa 2.2.0 as soon as I clicked the new project button (only on ubuntu, only once it occurred)  - @Bobbykumar706584 

- [x] Unable to see the first line in the editor after changing the chapter 

- [x] New book is not loading sometimes (waited long enough to confirm) 

- [x] OBS resources are not loading at all.

- [x] Language Combo box selection not working some times ( obs resource collection )
- [x] Obs meta creation issue only on beta tester system (always ingredients instead of path name in yaml (content/ingredients))
- [x] font size is not increasing/decreasing

**Loading Issues**
	
- [x] While project creation, when we create text translation project is taking more time than the audio translation and OBS.

- [x] #795

- [x] Bible resource collection: after selecting or download a project, always have to close the pane and reopen to reflect it in the Bible resource collection pane.

- [x] After recording the verse, have to click on the verse on editor pane to refreshing the audio which is recoded

**Comment by sijumoncy** [comment]
- [ ] Language Combo box selection not working some times ( obs resource collection )
- [ ] Obs meta creation issue only on beta tester system (always ingredients instead of path name in yaml (content/ingredients))
