### ISSUE TITLE
Sync UI Issues

### ISSUE THREAD

**Issue by joelthe1** [friendsofagape/autographa#693]
- [x] Door43.org logo not showing up
- [x] Once a project is uploaded the listing on the right is not automatically updated
- [x] The listing on the left pane is showing projects that are archived (those should be excluded from the list). This should work even if the archived flag is not present for projects that were created in earlier versions.

See video for example

https://user-images.githubusercontent.com/8311862/202637391-2bf72b76-eab0-41fa-8df8-79e4ce24989f.mov

**Comment by sijumoncy** [comment]
PR #696 
Fixed Issues
- Achieved Projects showing in sync left pane
- Auto update left sync pane after sync back to Ag

 PR #705 
- Right Pane auto update after upload

PR #713 
- Fixed logo issue PNG replaced with SVG
