### ISSUE TITLE
Login Issue : Not showing user after login

### ISSUE THREAD

**Issue by sijumoncy** [friendsofagape/autographa#740]
- [x] Sometimes the user is not showing in the profile section after login or after  creating a new user.
- [x] app navigate to project list page without proper user( may be no user token or not getting inside the app )
- [x] In new user creation user is created in the backend but not update it in UI .

![image](https://user-images.githubusercontent.com/72241997/210315208-55a0e3d7-c4b7-4c14-ab7b-e185171452e3.png)

**Comment by Bobbykumar706584** [comment]
user is displaying while login/logout/creating.
created user displaying on UI.

**Comment by Bobbykumar706584** [comment]
- [x] fixed the user is showing in the profile section after login
 - [x] fixed app navigates to the project list page with the proper user.
 - [x] fixed without user and token can't log in.
 - [x] fixed if there is no user, the page will return login page 
 - [x] fixed if a new user creation user is created in the backend but not updated it in the UI

need to fix: 
- [x] every time when we log in we need to click twice (need to update project list page).

**Comment by vipinpaul** [comment]
closed
