### ISSUE TITLE
Export Verse vise audio Bug

### ISSUE THREAD

**Issue by sijumoncy** [friendsofagape/autographa#798]
The format of export verse wise audio format is not in the proper format . It should be in with right params as mentioned in the audio department mail.

**Comment by vipinpaul** [comment]
The audio generated using js will not support the formats given by the audio department, and we are using media recorder API and it won't provide us with the requirement raised by the Audio department.

https://blog.addpipe.com/mediarecorder-api/


<span><p style="margin-bottom: 30px; margin-left: 0px;">The <strong>audio codec</strong> used is:</p><ul><li>Vorbis @ 44100 Hz on Firefox 30+</li><li>Opus Audio @ 48000 Hz on Chrome 49+</li></ul>

  | CHROME 49+ | CHROME 52+ | FIREFOX 30 AND UP
-- | -- | -- | --
Container | webm | webm | webm
Video codec | VP8/VP9 | VP8/VP9/H.264 | VP8
Audio codec | Opus @ 48kHz | Opus @ 48kHz | Vorbis @ 44.1 kHz

<p style="margin-bottom: 30px; margin-left: 0px;">Not quite the standard .MP4 file with H.264 video and AAC audio</p></span>
</span>
</span></span></span>
